[[check]]
name = "release-clippy"
mode = "cargo"
command = [
  "cargo",
  "clippy",
  "--lib",
  "--bins",
  "--release",
  "--locked",
  "--message-format=json",
  "--",
  "-D",
  "warnings",
]

[[check]]
name = "build"
mode = "cargo"
command = ["cargo", "build", "--all", "--locked", "--message-format=json"]

[[check]]
name = "test"
mode = "cargo"
command = [
  "cargo",
  "test",
  "--all",
  "--locked",
  "--message-format=json",
  "--",
  "--test-threads=1",
]

[[group]]
name = "all"
checks = ["format-check", "clippy", "release-clippy", "build", "test"]
